
server:
  address:
  port: 8081
  servlet:
    context-path: /hotdog
  tomcat:
    uri-encoding: UTF-8

mybatis-plus:
  mapper-locations: classpath:mapper/hotdog/module/*/*Mapper.xml
  typeAliasesPackage: cn.raysonblog.hotdog.module.*.entity
  global-config:
    id-type: 1
    db-column-underline: false
    refresh-mapper: true
    # capital-mode: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    lazyLoadingEnabled: false
    multipleResultSetsEnabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helper-dialect: mysql
  reasonable: false
  support-methods-arguments: true
  params: count=countSql

spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: /static/**,WEB-INF/views/**

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hotdog?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
    password:
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j2
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

logging:
  config: classpath:log4j2.xml
  level:
    root: info
    web: info
  file: logs/raytoo.log
